services:
  app:
    build: .
    ports:
      - "5555:5555"
    environment:
      - PROJECT_NAME=openai_app

      - REDIS_USER=user
      - REDIS_PASSWORD=pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_USERNAME=super_secret
      - SECRET_PASSWORD=very_secret

      - OPENAI_API_KEY=<your api key>

      - AUTO_RELOAD=true
      - DEBUG=false
    volumes:
      - .:/app/
    links:
      - redis
    depends_on:
      redis:
        condition: service_healthy
    command: bash -c "python3 main.py runserver"
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
