[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
skip = ["venv", "migrations"]

[tool.black]
line-length = 88
target-version = ["py312"]
preview = true
exclude = '''
/(
  | venv
  | migrations
)/
'''

[tool.autoflake]
recursive = true
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true
exclude = ["venv", "migrations"]